version: 1.{build}
image: Visual Studio 2017
install:
- ps: nuget restore LParserC.sln
build:
  verbosity: minimal
test_script:
- ps: >-
    dotnet vstest "C:\projects\lparserc\LParserCUnitTest\bin\Debug\netcoreapp2.1\LParserCUnitTest.dll" --ListTests
    dotnet vstest "C:\projects\lparserc\LParserCUnitTest\bin\Debug\netcoreapp2.1\LParserCUnitTest.dll" --Parallel
artifacts:
  - path: C:\projects\lparserc\LParserCUnitTest\bin\Debug\netcoreapp2.1\LParserCUnitTest.dll
